version: "3"

services:
  registry:
    image: registry:2
    ports:
      - 5000:5000

  registry_browser:
    image: klausmeyer/docker-registry-browser
    ports:
      - "8888:8080"
    environment:
      - SECRET_KEY_BASE=vDHDHDHDHDhshshshalue
  # visualizer:
  #   image: dockersamples/visualizer
  #   ports:
  #     - "9999:8080"
  #   volume:
  #     - /var/run/docker.sock:/var/run/docker.sock

  #     docker run -it -d -p 8080:8080 -v /var/run/docker.sock:/var/run/docker.sock dockersamples/visualizer
