version: "3.8"

services:
  web:
    image: ${DOCKERHUB_USERNAME}/app:latest # From Docker Hub
    build:
      context: ./app # Ensure this path is correct
      dockerfile: Dockerfile
    restart: always
    networks:
      - backend
    depends_on:
      - db
      - redis
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static-volume:/home/app/web/staticfiles
      - media-volume:/home/app/web/mediafiles
    expose:
      - 8000

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
  db:
    image: postgres:latest
    restart: always
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 10s
      retries: 3
  r-proxy:
    build: ./nginx
    image: ${DOCKERHUB_USERNAME}/r-proxy:latest
    networks:
      - backend
    depends_on:
      - web
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles

  redis:
    image: redis
    networks:
      - backend

  adminer:
    image: adminer
    networks:
      - backend
    restart: always
    ports:
      - 8080:8080

  dozzle:
    networks:
      - backend

    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9999:8080"

  pgadmin:
    networks:
      - backend
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_CONFIG_SERVER_MODE=OFF
      - PGADMIN_CONFIG_ENABLE_CSRF_PROTECTION=False
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=DEBUG
      - PGADMIN_CONFIG_FILE_LOG_LEVEL=DEBUG
      - PGADMIN_CONFIG_ENABLE_BINARY_IMAGE_UPLOAD=True
      - PGADMIN_CONFIG_ENABLE_FILE_UPLOAD=True
      - PGADMIN_CONFIG_ENABLE_SERVER_GROUPS=True
      - PGADMIN_CONFIG_ENABLE_USER_MANAGEMENT=True
      - PGADMIN_CONFIG_ENABLE_SERVER_MODE=False
      - PGADMIN_CONFIG_LOGIN_BANNER="Authorisedusers"
    ports:
      - "5050:80"
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  backend:
    driver: bridge
