---
- name: Set up Nginx and PostgreSQL on Ubuntu 22
  hosts: all
  become: true

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
        when: nginx_test.rc == 0

    - name: Restart PostgreSQL
      service:
        name: postgresql
        state: restarted

  tasks:
    # Update and upgrade the system
    - name: Update apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Ensure Python is installed
      become: yes
      apt:
        name: python3
        state: present


    - name: Install net-tools (for netstat)
      apt:
        name: net-tools
        state: present
        update_cache: yes

    # Install Nginx
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure Nginx is enabled and running
      service:
        name: nginx
        state: started
        enabled: yes
    # Install PostgreSQL
    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Ensure PostgreSQL is enabled and running
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Allow Nginx Full profile through UFW
      ufw:
        rule: allow
        name: "Nginx Full"

    - name: Allow PostgreSQL through UFW
      ufw:
        rule: allow
        port: 5432
        proto: tcp

    - name: Create directory for static files
      file:
        path: /var/www/static
        state: directory
        owner: www-data
        group: www-data
        mode: "0755"

    - name: Create directory for media files
      file:
        path: /var/www/media
        state: directory
        owner: www-data
        group: www-data
        mode: "0755"
    - name: Restore default nginx.conf
      copy:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: "0644"

    