---
- name: Install Docker and Docker Compose
  hosts: all
  become: yes # Run as sudo
  roles:
    - role: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker-compose # Installs standalone Docker Compose via pip

    - role: geerlingguy.docker
      vars:
        docker_users: "{{ ansible_user }}" # Add the current user to the docker group
        docker_group: docker
          - "{{ ansible_user }}"
        docker_install_compose: false
